# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jsc < Formula
  desc "A tool that joins multiple slack channels to display posts in chronological order."
  homepage "https://github.com/michimani/jsc"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/michimani/jsc/releases/download/v0.1.0/jsc_0.1.0_darwin_arm64.tar.gz"
      sha256 "1bf1909a049377c79182e9a9a0d15786f89c9a4d8ceb88b13e6a1168fc30b16d"

      def install
        bin.install "jsc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/michimani/jsc/releases/download/v0.1.0/jsc_0.1.0_darwin_x86_64.tar.gz"
      sha256 "93ab74155bcf0be08a7b04cc2ba8a2d9aeea370bd0150a32269509ccf40cd049"

      def install
        bin.install "jsc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/michimani/jsc/releases/download/v0.1.0/jsc_0.1.0_linux_arm64.tar.gz"
      sha256 "6e3d43039e93162e76ba34d0e80585bd46b298bfbf454db1a3084536a2bebf9b"

      def install
        bin.install "jsc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/michimani/jsc/releases/download/v0.1.0/jsc_0.1.0_linux_x86_64.tar.gz"
      sha256 "09fd0c67a9e50345d1c362938f55e471fc4cfb8fa0764d240a5dad16e3579ba0"

      def install
        bin.install "jsc"
      end
    end
  end
end
